name = "test"
description = "just a test template for quick"
after_get_message = "\n\nUse 'python main.py' bro\n\n"

ignore = ["test.py"]

[[varfiles]]
path = "main.py"

  [[varfiles.variables]]
  name = "{{name}}"
  prompt = "Enter your name: "
